x-default-deploy: &default-deploy
  replicas: ${MINIO_REPLICAS:-3}
  placement:
    max_replicas_per_node: 1
    constraints:
      - node.labels.minio == true
    preferences:
      - spread: "node.labels.minio"
  update_config:
    parallelism: 1
    delay: 30s
    order: stop-first
    failure_action: rollback
  rollback_config:
    parallelism: 1
    delay: 30s
  restart_policy:
    condition: on-failure
    delay: 30s
    max_attempts: 3
    window: 120s

x-default-logging: &default-logging
  options:
    max-size: "12m"
    max-file: "5"
  driver: json-file

services:
  minio:
    image: quay.io/minio/minio:${MINIO_VERSION:-latest}
    command: server --console-address ":9001" ${MINIO_SERVER_CLUSTER_URL:-/data}
    hostname: minio-{{.Task.Slot}}
    networks:
      - minio
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minioadmin}
      MINIO_CONFIG_ENV_FILE: /minio/config.env
    volumes:
      - minio-data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    deploy: *default-deploy
    logging: *default-logging

  nginx:
    image: nginx:stable-alpine
    networks:
      - minio
    ports:
      - 9000:9000
      - 9001:9001
    configs:
      - source: default.conf.template
        target: /etc/nginx/templates/default.conf.template
      - source: nginx_startup-delay.sh
        target: /docker-entrypoint.d/99-nginx_startup-delay.sh
        mode: 0755
    depends_on:
      - minio
    deploy: *default-deploy
    logging: *default-logging

networks:
  minio:

volumes:
  minio-data:
    name: minio-data
    external: true

configs:
  default.conf.template:
    name: minio_nginx_default.conf.template
    file: services/nginx/default.conf.template
  nginx_startup-delay.sh:
    name: minio_nginx_startup-delay.sh
    file: services/nginx/startup-delay.sh
