# ----------------------------------
# MinIO Single Deployment
# ----------------------------------
services:
  minio:
    command: server --console-address ":9001" /data
    deploy:
      replicas: 1
      placement:
        max_replicas_per_node: 1
        constraints:
          - node.labels.minio == true
        preferences:
          - spread: "node.labels.minio"

  ingress:
    deploy:
      replicas: 1
      placement:
        max_replicas_per_node: 1
        constraints:
          - node.labels.minio == true
        preferences:
          - spread: "node.labels.minio"
