x-default-deploy: &default-deploy
  update_config:
    parallelism: 1
    delay: 30s
    order: stop-first
    failure_action: rollback
  rollback_config:
    parallelism: 1
    delay: 30s
  restart_policy:
    condition: on-failure
    delay: 30s
    max_attempts: 3
    window: 120s

x-default-logging: &default-logging
  options:
    max-size: "12m"
    max-file: "5"
  driver: json-file

networks:
  minio:

configs:
  # Minio configuration
  minio.env:
    file: services/minio/config.env
  # Ingress configuration
  default.conf.template:
    file: services/nginx/default.conf.template
  nginx_startup-delay.sh:
    file: services/nginx/startup-delay.sh

services:
  minio:
    image: minio/minio:${MINIO_VERSION:-latest}
    hostname: minio-{{.Task.Slot}}
    networks:
      - minio
    environment:
      MINIO_CONFIG_ENV_FILE: /minio/config.env
    configs:
      - source: minio.env
        target: /minio/config.env
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
    #   interval: 30s
    #   timeout: 20s
    #   retries: 3
    deploy: *default-deploy
    logging: *default-logging

  ingress:
    image: nginx:${MINIO_NGINX_VERSION:-stable-alpine}
    networks:
      - minio
    ports:
      - ${MINIO_PORT:-9000}:9000
      - ${MINIO_CONSOLE_PORT:-9001}:9001
    configs:
      - source: default.conf.template
        target: /etc/nginx/templates/default.conf.template
      - source: nginx_startup-delay.sh
        target: /docker-entrypoint.d/99-nginx_startup-delay.sh
        mode: 0755
    depends_on:
      - minio
    deploy: *default-deploy
    logging: *default-logging
